// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvUFbe_7V7bEaRhV0v37u3hUOqmq2KP3w',
    appId: '1:974985211075:android:30c78e5d73a863d963c676',
    messagingSenderId: '974985211075',
    projectId: 'chat-app-b85a2',
    storageBucket: 'chat-app-b85a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP2jfFdGmn560EN6Frt4qZLmW3UJi3kVI',
    appId: '1:974985211075:ios:2afc08615396933463c676',
    messagingSenderId: '974985211075',
    projectId: 'chat-app-b85a2',
    storageBucket: 'chat-app-b85a2.firebasestorage.app',
    iosBundleId: 'com.example.lioraFlutter',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP2jfFdGmn560EN6Frt4qZLmW3UJi3kVI',
    appId: '1:974985211075:web:2afc08615396933463c676',
    messagingSenderId: '974985211075',
    projectId: 'chat-app-b85a2',
    storageBucket: 'chat-app-b85a2.firebasestorage.app',
  );    
}
